package dbConection;


import java.sql.SQLException;


public class pruebas {

	public static void main(String[] args) throws SQLException {
		/*ConnectionDB factory = new ConnectionDB();
		Connection con = factory.recuperaConexion();
		ReservaDAO reserva = new ReservaDAO (con);
		HuespedDAO huespedDao = new HuespedDAO(con);
		UserDAO user = new UserDAO(con);
		
		huespedDao.validarExitenciaHuesped("ESTADOUNIDENSE", "77154886");

		//LocalDate fecha = LocalDate.of(2000, 5, 18);
		
		//Reserva uwu = new Reserva(4,fecha, fecha, 145.20, FormaPago.TRANSFERENCIA);
		
		//reserva.modificar(4,fecha, fecha, 200.50, FormaPago.EFECTIVO,1);
		
		user.authenticate("admin", "admin");

		
		System.out.println(reserva.listar());*/
		

	}

}
